spring:
  cloud:
    azure:
      eventhub:
        connection-string: ${EH_CONNECTION_STRING}
        checkpoint-storage-account: ${STORAGE_ACCOUNT}
        checkpoint-access-key: ${STORAGE_KEY}
        checkpoint-container: ${STORAGE_CONTAINER}

    stream:
      bindings:
        consume-in-0:
          destination: ${EH_EVENT_HUB}
          group: ${EH_CONSUMER_GROUP}
          # partitioned: true
        supply-out-0:
          destination: ${EH_EVENT_HUB}

      eventhub:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      #  function:
      #    definition: consume;supply;
      poller:
        initial-delay: 0
        fixed-delay: 10000

---
spring:
  config:
    activate:
      on-profile: web
  cloud:
    # stream:
    function:
      definition: supply
---
spring:
  config:
    activate:
      on-profile: consumer
  cloud:
    # stream:
    function:
      definition: consume

---
spring:
  config:
    activate:
      on-profile: "!web"

# this will disable tomcat if web not running
  main:
    web-application-type: none